[project]
name = "cloudrun-example"
version = "0.1.0"
dependencies = [
    "flask~=2.3.2",
    "gunicorn~=21.2.0",
]
requires-python = ">=3.13"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
