[project]
name = "iac"
version = "0.1.0"
dependencies = [
    "cdktf",
    "google-auth",
    "cdktf-cdktf-provider-google"
]
requires-python = ">=3.13"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
